vim.cmd([[packadd packer.nvim]])

require("packer").startup(function()
        use("wbthomason/packer.nvim")
        use("tpope/vim-fugitive")
        use("tpope/vim-rhubarb")
        use({ "nvim-lualine/lualine.nvim", requires = { "kyazdani42/nvim-web-devicons", opt = true } })
        use({ "neovim/nvim-lspconfig", after = "mason.nvim" })
        use({ "tami5/lspsaga.nvim", after = "mason.nvim" })
        use({ "folke/lsp-colors.nvim", after = "mason.nvim" })
        use("L3MON4D3/LuaSnip")
        use("hrsh7th/cmp-nvim-lsp")
        use({ "hrsh7th/cmp-buffer", after = "nvim-cmp" })
        use("hrsh7th/nvim-cmp")
        use({ "onsails/lspkind-nvim", after = "mason.nvim" })
        use({ "nvim-treesitter/nvim-treesitter", after = { colorscheme } })
        use("nvim-lua/popup.nvim")
        use("nvim-lua/plenary.nvim")
        use({ "nvim-telescope/telescope.nvim", after = { colorscheme } })
        use("windwp/nvim-autopairs")
        use("akinsho/toggleterm.nvim")
        use("rcarriga/nvim-notify")
        use("williamboman/mason.nvim")
        use({ "williamboman/mason-lspconfig.nvim", after = { "mason.nvim", "nvim-lspconfig", "cmp-nvim-lsp" } })
        use("goolord/alpha-nvim")
        use({ "j-hui/fidget.nvim", after = { "mason.nvim" } })
        use({ "akinsho/bufferline.nvim", tag = "v2.*", requires = "kyazdani42/nvim-web-devicons", after = { colorscheme } })
        use("sidebar-nvim/sidebar.nvim")
        use("lukas-reineke/indent-blankline.nvim")
        use("petertriho/nvim-scrollbar")
        use("yioneko/nvim-yati")
        use({ "folke/trouble.nvim", after = "mason.nvim" })
        use({ "nvim-telescope/telescope-file-browser.nvim", after = "telescope.nvim" })
        use("simrat39/rust-tools.nvim")
        use("EdenEast/nightfox.nvim")
        use({ "jose-elias-alvarez/null-ls.nvim", after = "mason.nvim" })
end)
